public enum TipoToken {
    IRRIGAR, SENSOR, DISPOSITIVO, SE, SENAO, LIGAR, DESLIGAR, PAUSAR, REPETIR, A_CADA, MINUTO,
    VIRGULA, IGUAL, ABRE_PARENTESE, FECHA_PARENTESE, ABRE_CHAVE, FECHA_CHAVE, OPERADOR_RELACIONAL, VALOR, IDENTIFICADOR
}
